# Generated by Django 4.1.7 on 2023-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marker',
            field=models.BooleanField(default=False),
        ),
    ]
